// <auto-generated />
using System;
using Homeapp.Backend.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homeapp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Homeapp.Backend.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SharedEntitiesId")
                        .HasColumnType("char(36)");

                    b.Property<double>("StartingBalance")
                        .HasColumnType("double");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SharedEntitiesId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatingUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SharedEntitiesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatingUserId");

                    b.HasIndex("SharedEntitiesId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.IncomeCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatingUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SharedEntitiesId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatingUserId");

                    b.HasIndex("SharedEntitiesId");

                    b.ToTable("IncomeCategories");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.RecurringSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnnualDateMonthDate")
                        .HasColumnType("int");

                    b.Property<int>("AnnualMonth")
                        .HasColumnType("int");

                    b.Property<int>("DateOfMonth")
                        .HasColumnType("int");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("RecurringType")
                        .HasColumnType("int");

                    b.Property<int>("SecondAnnualDateMonthDate")
                        .HasColumnType("int");

                    b.Property<int>("SecondAnnualMonth")
                        .HasColumnType("int");

                    b.Property<int>("SecondDateOfMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecurringSchedules");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.RecurringTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<Guid>("CreatingUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ExpenseCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IncomeCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("RecurringScheduleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SharedEntitiesId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatingUserId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("IncomeCategoryId");

                    b.HasIndex("RecurringScheduleId");

                    b.HasIndex("SharedEntitiesId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.SharedEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EditHouseholdGroupIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EditHouseholdIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("EditUserIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReadHouseholdGroupIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReadHouseholdIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReadUserIds")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("SharedEntities");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountIdToTransferTo")
                        .HasColumnType("char(36)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ExpenseCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IncomeCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RecurringTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SharedEntitiesId")
                        .HasColumnType("char(36)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("IncomeCategoryId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RecurringTransactionId");

                    b.HasIndex("SharedEntitiesId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.HouseholdGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("HouseholdGroups");
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.UserHousehold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHouseholds");
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.UserHouseholdGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HouseholdGroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHouseholdGroups");
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.Account", b =>
                {
                    b.HasOne("Homeapp.Backend.Entities.SharedEntities", "SharedEntities")
                        .WithMany()
                        .HasForeignKey("SharedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.ExpenseCategory", b =>
                {
                    b.HasOne("Homeapp.Backend.Identity.User", "CreatingUser")
                        .WithMany()
                        .HasForeignKey("CreatingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.SharedEntities", "SharedEntities")
                        .WithMany()
                        .HasForeignKey("SharedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.IncomeCategory", b =>
                {
                    b.HasOne("Homeapp.Backend.Identity.User", "CreatingUser")
                        .WithMany()
                        .HasForeignKey("CreatingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.SharedEntities", "SharedEntities")
                        .WithMany()
                        .HasForeignKey("SharedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("Homeapp.Backend.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Identity.User", "CreatingUser")
                        .WithMany()
                        .HasForeignKey("CreatingUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId");

                    b.HasOne("Homeapp.Backend.Entities.IncomeCategory", "IncomeCategory")
                        .WithMany()
                        .HasForeignKey("IncomeCategoryId");

                    b.HasOne("Homeapp.Backend.Entities.RecurringSchedule", "RecurringSchedule")
                        .WithMany()
                        .HasForeignKey("RecurringScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.SharedEntities", "SharedEntities")
                        .WithMany()
                        .HasForeignKey("SharedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Entities.Transaction", b =>
                {
                    b.HasOne("Homeapp.Backend.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.ExpenseCategory", "ExpenseCategory")
                        .WithMany()
                        .HasForeignKey("ExpenseCategoryId");

                    b.HasOne("Homeapp.Backend.Entities.IncomeCategory", "IncomeCategory")
                        .WithMany()
                        .HasForeignKey("IncomeCategoryId");

                    b.HasOne("Homeapp.Backend.Identity.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.RecurringTransaction", "RecurringTransaction")
                        .WithMany()
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Entities.SharedEntities", "SharedEntities")
                        .WithMany()
                        .HasForeignKey("SharedEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.HouseholdGroup", b =>
                {
                    b.HasOne("Homeapp.Backend.Identity.Household", "Household")
                        .WithMany("HouseholdGroups")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.UserHousehold", b =>
                {
                    b.HasOne("Homeapp.Backend.Identity.Household", "Household")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Identity.User", "User")
                        .WithMany("Households")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Homeapp.Backend.Identity.UserHouseholdGroup", b =>
                {
                    b.HasOne("Homeapp.Backend.Identity.HouseholdGroup", "HouseholdGroup")
                        .WithMany("Users")
                        .HasForeignKey("HouseholdGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Homeapp.Backend.Identity.User", "User")
                        .WithMany("HouseholdGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
